import { Metadata } from 'next';
import Link from 'next/link';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Showcase | VideoViber',
  description: 'Pro renders generated by the VideoViber engine.',
};

const DUMMY_RENDERS = [
  {
    id: 'render-001',
    title: 'Neon District Override',
    creator: 'Director K.',
    engine: 'Veo-2',
    imgUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&auto=format&fit=crop&q=80',
    aspect: 'aspect-video',
  },
  {
    id: 'render-002',
    title: 'Orbital Genesis',
    creator: 'Space Dynamics',
    engine: 'Gemini-1.5',
    imgUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80',
    aspect: 'aspect-[4/5]',
  },
  {
    id: 'render-003',
    title: 'Synthetic Portraits',
    creator: 'Studio 9',
    engine: 'Veo-2',
    imgUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80',
    aspect: 'aspect-[3/4]',
  },
  {
    id: 'render-004',
    title: 'Quantum Holodeck',
    creator: 'Visuals By T.',
    engine: 'Veo-1',
    imgUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
    aspect: 'aspect-square',
  },
  {
    id: 'render-005',
    title: 'Neural Landscape',
    creator: 'Deep Render Co.',
    engine: 'Gemini-Flash',
    imgUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80',
    aspect: 'aspect-video',
  },
  {
    id: 'render-006',
    title: 'Chromatic Void',
    creator: 'Aesthetic.io',
    engine: 'Veo-2',
    imgUrl: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=800&auto=format&fit=crop&q=80',
    aspect: 'aspect-[4/5]',
  },
];

export default function ShowcasePage() {
  const cookieStore = cookies();
  const isLoggedIn =
    cookieStore.get('admin_bypass')?.value === 'true' ||
    cookieStore.getAll().some((c) => c.name.startsWith('sb-') && c.name.endsWith('-auth-token'));

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#02040a] pb-24 pt-32">
      {/* Background Gradients */}
      <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(1200px_600px_at_50%_-20%,rgba(82,222,255,0.1),transparent_70%),radial-gradient(800px_500px_at_100%_40%,rgba(255,175,103,0.05),transparent_60%)]" />

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl text-center">
          <p className="text-cyan-200 text-sm font-semibold uppercase tracking-[0.15em] mb-4">
            Studio Showcase
          </p>
          <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl mb-6">
            Pro Tools. Pure Power.
          </h1>
          <p className="text-vv-secondary text-lg leading-relaxed">
            A curated gallery of scenes rendered through the VideoViber engine. Witness the fidelity of true continuity mapping and semantic editing parameters.
          </p>
          <div className="mt-10 flex justify-center gap-4">
            {isLoggedIn ? (
              <Link href="/dashboard" className="vv-btn-primary px-8 py-3.5 text-sm font-medium">
                Go to Dashboard
              </Link>
            ) : (
              <Link href="/login" className="vv-btn-primary px-8 py-3.5 text-sm font-medium">
                Initialize Scene
              </Link>
            )}
            <Link href="/features" className="vv-btn-secondary px-8 py-3.5 text-sm font-medium">
              Explore Engine
            </Link>
          </div>
        </div>

        <div className="mt-24 columns-1 gap-6 sm:columns-2 lg:columns-3">
          {DUMMY_RENDERS.map((render, i) => (
            <div
              key={render.id}
              className={`group relative mb-6 overflow-hidden rounded-2xl bg-white/5 ring-1 ring-white/10 ${render.aspect}`}
              style={{
                animationDelay: `${i * 100}ms`,
                // Simulate stagger fade in
                animation: 'fade-in-up 0.8s ease-out forwards',
                opacity: 0,
              }}
            >
              {/* Image element replacing Next/Image for simplicity and immediate cross-domain support */}
              <img
                src={render.imgUrl}
                alt={render.title}
                className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"
                loading="lazy"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-60 transition-opacity duration-300 group-hover:opacity-100" />
              
              <div className="absolute inset-x-0 bottom-0 p-6 translate-y-4 opacity-0 transition-all duration-300 ease-out group-hover:translate-y-0 group-hover:opacity-100">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-lg font-bold text-white tracking-tight">{render.title}</h3>
                    <p className="text-sm text-vv-secondary mt-1 overflow-hidden text-ellipsis whitespace-nowrap">By {render.creator}</p>
                  </div>
                  <div className="shrink-0 bg-white/10 backdrop-blur-md ring-1 ring-white/20 px-3 py-1 rounded-full text-xs font-mono text-cyan-200">
                    {render.engine}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
      
      {/* Global CSS for fade-in since we used standard style attribute */}
      <style dangerouslySetInnerHTML={{__html: `
        @keyframes fade-in-up {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}} />
    </div>
  );
}
